project:
  type: website
  output-dir: docs

website:
  title: "Ramdhan's Blog"
  navbar:
    right:
      - text: About Me
        href: about.qmd    
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
    
format:
  html:
    theme: 
      light: flatly
      dark: superhero
    css: styles.css
    code-fold: true
    code-link: true
    
editor: visual

